#!/usr/bin/env -S expect -f

set timeout 3
spawn ../../bin/composer_install.sh "lowest" "--ignore-platform-reqs --optimize-autoloader" "../fixtures/with-lock-file" "" "" "../fixtures/with-lock-file/composer.lock"
match_max 100000

expect "::debug::Using the following Composer command: '*/php */composer update --no-interaction --no-progress --ansi --prefer-lowest --prefer-stable --ignore-platform-reqs --optimize-autoloader --working-dir ../fixtures/with-lock-file'"
expect "Updating dependencies"
expect "Generating optimized autoload files"
expect eof

# Clean up
file delete -force ../fixtures/with-lock-file/vendor
