#!/usr/bin/env -S expect -f

set timeout 3
spawn ../../bin/composer_install.sh "highest" "" "../fixtures/with-lock-file" "" "" "../fixtures/with-lock-file/composer.lock"
match_max 100000

expect "::debug::Using the following Composer command: '*/php */composer update --no-interaction --no-progress --ansi --working-dir ../fixtures/with-lock-file'"
expect "Updating dependencies"
expect "Generating autoload files"
expect eof

# Clean up
file delete -force ../fixtures/with-lock-file/vendor
