#!/usr/bin/env -S expect -f

set timeout 3
spawn ../../bin/composer_install.sh "lowest" "" "../fixtures/with-lock-file" "" "" "../fixtures/with-lock-file/composer.lock"
match_max 100000

expect "::debug::Using the following Composer command: '*/composer update --no-interaction --no-progress --ansi --prefer-lowest --prefer-stable --working-dir ../fixtures/with-lock-file'"
expect "Updating dependencies"
expect "Generating autoload files"
expect eof

# Clean up
file delete -force ../fixtures/with-lock-file/vendor
