#!/usr/bin/env -S expect -f

set timeout 3
spawn ../../bin/composer_paths.sh "" "../fixtures/with-lock-file"
match_max 100000

expect "::notice title=Composer Path::Composer path is '*'\r
::notice title=Composer Cache::Composer cache directory found at '*'\r
::notice title=composer.json::File composer.json found at '../fixtures/with-lock-file/composer.json'\r
::notice title=composer.lock::File composer.lock path computed as '../fixtures/with-lock-file/composer.lock'\r
::set-output name=command::*\r
::set-output name=cache-dir::*\r
::set-output name=json::../fixtures/with-lock-file/composer.json\r
::set-output name=lock::../fixtures/with-lock-file/composer.lock\r
"
expect eof
