#!/usr/bin/env -S expect -f

set timeout 3
spawn ../../bin/composer_install.sh "highest" "" "test-subdir"
match_max 100000

expect -exact "::notice title=Composer::Using the following Composer command: 'composer update --no-interaction --no-progress --ansi  --working-dir test-subdir'"
expect "Updating dependencies"
expect "Installing dependencies from lock file (including require-dev)"
expect "Generating autoload files"
expect eof
