#!/usr/bin/env -S expect -f

set timeout 3
spawn ../../bin/composer_install.sh "" "" "../fixtures/no-lock-file" "" "" ""
match_max 100000

expect "::debug::Using the following Composer command: '*/php */composer update --no-interaction --no-progress --ansi --working-dir ../fixtures/no-lock-file'"
expect "Updating dependencies"
expect "Writing lock file"
expect "Generating autoload files"
expect eof

# Clean up
file delete -force ../fixtures/no-lock-file/vendor
file delete -force ../fixtures/no-lock-file/composer.lock
