#!/usr/bin/env -S expect -f

set timeout 3
spawn ../../bin/composer_install.sh "highest" "--ignore-platform-reqs --optimize-autoloader" "" "" "" "composer.lock"
match_max 100000

expect "::debug::Using the following Composer command: '*/composer update --no-interaction --no-progress --ansi --ignore-platform-reqs --optimize-autoloader'"
expect "Updating dependencies"
expect "Generating optimized autoload files"
expect eof

# Clean up
file delete -force vendor
